### ISSUE TITLE
not really minimalist, it just looks like it

### ISSUE THREAD

**Issue by PVNFU-28** [makkoncept/Mingo#2]
it LOOKS minimalist but the code is actually full of unnecessary spaces and lines, im not a professional web-dev, without actually inspecting the code and how it works, and just deleting unnecessary spaces and lines i made it 820 bytes lighter which is a lot in a project this size, im just saying, minimalism isnt just looks, bloated code isnt minimalist.

**Comment by makkoncept** [comment]
Hi @panfu28, thanks for the feedback!.
maybe you can submit a PR with the change that you have made.
Thanks!
